services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    ports:
      - "${EXPOSE_APP_PORT}:3000"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
    ports:
      - "${EXPOSE_DATABASE_PORT}:3306"
    volumes:
      - fastify_db_data:/var/lib/mysql

volumes:
  backend_node_modules:
  fastify_db_data: