services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./backend:/app
      - nodejs-app-backend-node-modules:/app/node_modules
    networks:
      - nodejs-app-backend-network
    ports:
      - "${EXPOSE_APP_PORT}:3000"
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
    networks:
      - nodejs-app-backend-network
    ports:
      - "${EXPOSE_DATABASE_PORT}:3306"
    volumes:
      - nodejs-app-backend-data:/var/lib/mysql

networks:
  nodejs-app-backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.35.4.0/24

volumes:
  nodejs-app-backend-node-modules:
  nodejs-app-backend-data: